### ISSUE TITLE
Problem compiling using Visual Studio 2010

### ISSUE THREAD

**Issue by jberzy** [OpenRTMFP/Cumulus#21]
Hello,

Great Job on the server!  

I've successfully compiled the server on Ubuntu 10.10. However when I tried to compile with VS 2010 on Windows I get the following compilation error:

2>  BinaryStream.cpp
2>include\BinaryStream.h(75): error C2039: '_Sgetn_s' : is not a member of 'std::basic_stringbuf<_Elem,_Traits,_Alloc>'
2>          with
2>          [
2>              _Elem=char,
2>              _Traits=std::char_traits<char>,
2>              _Alloc=std::allocator<char>
2>          ]

Any Suggestions?

Thanks
John

**Comment by thomasgeorgec** [comment]
what is the fix?

**Comment by thomasjammet** [comment]
I think [this commit](https://github.com/OpenRTMFP/Cumulus/commit/50479528ba5a74561ee6b67aaed04d8d3988466c#diff-a72f9c49561f9eef200e455160f92fd7) has fixed thes issue.
Tough Cumulus is not maintained since a long time, please give a try to [MonaServer2](https://github.com/MonaSolutions/MonaServer2) if you want to have the most up-to-date implementation of RTMFP and a lot of new features and fixes.
